# Set variables once
variables:
  solutionType: dotNetCore
  cleanCheckout: 'false'
  sonarCloudPrepareExtraProperties: |  
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
  integrationTestsAppSettingsTransform: ''
  vhAzureKeyVault: 'https://vhwebsitepreview.vault.azure.net/' # Used during integration tests
  keyVaultName: vhcoreinfrahtpreview # Used to get secrets for integration tests
  secretsFilter: 'vh-user-api-appid' # filters out secrets returned from key vault

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    endpoint: 'GitHub connection 1'
    ref: refs/heads/master  # ref name to use, defaults to 'refs/heads/master'


trigger:
- master
pr:
- master

jobs:
- template: jobs/angularDotNetCore.yml@azureDevOpsTemplates # Template reference
  parameters:
    cleanCheckout: $(cleanCheckout)
    sonarCloudExtraProperties: $(sonarCloudPrepareExtraProperties)
    KeyVaultName: $(KeyVaultName)
    SecretsFilter: $(SecretsFilter)
    solutionType: $(solutionType)
    integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
