# Set variables once
variables:
  apiDirectory: 'UserApi/UserApi'
  sonarCloudPrepareExtraProperties: |
    sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)\Coverage\coverage.opencover.xml
    sonar.coverage.exclusions="**/Program.cs,**/Startup.cs,Migrations/**,SeedData/**,DesignTimeHearingsContextFactory.cs,Ddd/ValueObject.cs,Ddd/Enumeration.cs,Testing.Common/**"
    sonar.cpd.exclusions="**/SeedData.cs,Migrations/**"
  coverletCoverageExclusions: '"\"[User.*Tests?]*,\""'
  integrationTestsAppSettingsTransform: '
    "AzureAd/Authority":"$(AzureAd-Authority)",
    "AzureAd/VhUserApiResourceId":"$(AzureAd-VhUserApiResourceId)",
    "ConnectionStrings/VhUser":"$(ConnectionStrings-VhUser)",
    "Testing/TestClientId":"$(Testing-TestClientId)",
    "Testing/TestClientSecret":"$(Testing-TestClientSecret)"
    '

# GitHub Repo that conatins build templates. Reference https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=vsts#using-other-repositories
resources:
  repositories:
  - repository: azureDevOpsTemplates
    type: github
    name: hmcts/azure-devops-templates
    ref: refs/heads/dotnet-restore # ref name to use, defaults to 'refs/heads/master'
    endpoint: 'GitHub connection 1'

trigger:
- master
pr:
- master

jobs:
  
- template: jobs/webapi.yml@azureDevOpsTemplates # Template reference
  parameters:
    sonarCloudExtraProperties: $(sonarCloudPrepareExtraProperties)
    integrationTestsAppSettingsTransform: $(integrationTestsAppSettingsTransform)
    coverletCoverageExclusions: $(coverletCoverageExclusions)
    apiDirectory: $(apiDirectory)